AGGREGATOR = 'FedAvg'
NUM_CLIENTS = 20
NUM_ROUNDS = 5
FRAC_FIT = 1.0
FRAC_EVALUATE = 1.0
MIN_FIT_CLIENTS = 10
MIN_EVALUABLE_CLIENTS = 5
MIN_AVAILABLE_CLIENTS = 10

#Data loading and training variables
DATASET = 'MNIST'
IID = true
ALFA = 1000
MODEL = 'MLP'
SEED = 42
VAL_SPLIT = 0.1
BATCH_SIZE = 32
EPOCHS = 5

#Simulation resources
CPUS = 2