#Federated variables
NUM_CLIENTS = 100
NUM_ROUNDS = 5
CLIENT_FRAC = 1.0
MIN_FIT_CLIENTS = 10
MIN_EVALUABLE_CLIENTS = 5
MIN_AVAILABLE_CLIENTS = 10

#Data loading and training variables
DATASET = 'MNIST'
SEED = 42
VAL_SPLIT = 0.1
BATCH_SIZE = 32
EPOCHS = 5